In [56]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt

In [57]:
# Grab and process the raw data.
data_path = ("https://raw.githubusercontent.com/Thinkful-Ed/data-201-resources/"
             "master/sms_spam_collection/SMSSpamCollection"
            )
sms_raw = pd.read_csv(data_path, delimiter= '\t', header=None)
sms_raw.columns = ['spam', 'message']

# Enumerate our spammy keywords.
keywords = ['click', 'offer', 'winner', 'buy', 'free', 'cash', 'urgent']

for key in keywords:
    sms_raw[str(key)] = sms_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
)

sms_raw['allcaps'] = sms_raw.message.str.isupper()
sms_raw['spam'] = (sms_raw['spam'] == 'spam')
data = sms_raw[keywords + ['allcaps']]
target = sms_raw['spam']

from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
y_pred = bnb.fit(data, target).predict(data)

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB

data1,data2,target1,target2 = train_test_split(data, target, test_size=0.5, random_state=20)

data11,data12,target11,target12 = train_test_split(data1, target1, test_size=0.5, random_state=20)
data21,data22,target21,target22 = train_test_split(data2, target2, test_size=0.5, random_state=20)


In [63]:
bnb = BernoulliNB()

bnb.fit(data11,target11)
y_pred = bnb.predict(data12)
cm12 = confusion_matrix(target12, y_pred)

bnb.fit(data21,target21)
y_pred = bnb.predict(data22)
cm22 = confusion_matrix(target22, y_pred)

bnb.fit(data12,target12)
y_pred = bnb.predict(data11)
cm11 = confusion_matrix(target11, y_pred)

bnb.fit(data22,target22)
y_pred = bnb.predict(data21)
cm21 = confusion_matrix(target21, y_pred)

In [77]:
print("cm12\n",cm12)
print("\n")
print("cm22\n",cm22)
print("\n")
print("cm11\n",cm11)
print("\n")
print("cm21\n",cm21)
print("\n")

cm12
 [[1182   14]
 [ 147   50]]


cm22
 [[1212   12]
 [ 128   41]]


cm11
 [[1187   17]
 [ 142   47]]


cm21
 [[1190   11]
 [ 138   54]]


